version: '3.8'

services:
  # 数据库服务
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    # Swarm 会自动将此服务连接到默认的 overlay 网络

  # API 服务
  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    # Swarm 会自动将此服务连接到默认的 overlay 网络

# 我们不再需要定义 network，让 Swarm 自动处理

# 定义数据卷，用于持久化存储数据库数据
volumes:
  db_data:
