version: '3.8'

services:
  # 数据库服务
  db:
    image: mysql:8.0
    # container_name 和 restart 在 Swarm 模式下被忽略，可以移除
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gongju-net

  # API 服务
  api:
    build: .
    # container_name 和 restart 在 Swarm 模式下被忽略，可以移除
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    networks:
      - gongju-net

# 定义网络
networks:
  gongju-net:
    # 关键改动：将驱动从 bridge 改为 overlay
    driver: overlay
    # 添加 attachable: true 允许我们连接到这个网络进行调试
    attachable: true

# 定义数据卷
volumes:
  db_data:
